#!/usr/bin/env bun
/**
 * Emit `dist/sw.js`: an app-shell service worker that precaches the built client so
 * the installed app opens instantly and offline. Runs after `bun build` (see the
 * `build` script).
 *
 * The cache name is derived from the precached file names and sizes. Bundles are
 * content-hashed, so any deploy that changes the client changes `sw.js`, which is
 * how browsers notice an update. The new worker installs the new shell and drops the
 * old cache. All URLs are relative, so the build works under a path prefix (GitHub
 * Pages project sites).
 */
import * as path from "node:path";

const dist = path.join(import.meta.dir, "..", "dist");

/** Site-root files the client never fetches; skipping them keeps the install small. */
const SKIP: Record<string, true> = { "sw.js": true, "og-image.png": true, "robots.txt": true, "sitemap.xml": true };

const files: string[] = [];
const fingerprint = new Bun.CryptoHasher("sha256");
for (const name of [...new Bun.Glob("*").scanSync({ cwd: dist, onlyFiles: true })].sort()) {
	if (SKIP[name]) continue;
	files.push(name);
	fingerprint.update(`${name}:${Bun.file(path.join(dist, name)).size}\n`);
}
if (!files.includes("index.html")) {
	console.error("build-sw: dist/index.html missing; run the bundle step first");
	process.exit(1);
}
const version = fingerprint.digest("hex").slice(0, 12);

const sw = `// Auto-generated by packages/collab-web/scripts/build-sw.ts - DO NOT EDIT
const CACHE = "omp-collab-${version}";
const SHELL = ${JSON.stringify(["./", ...files.map(f => `./${f}`)])};

self.addEventListener("install", event => {
	event.waitUntil(
		caches
			.open(CACHE)
			.then(cache => cache.addAll(SHELL))
			.then(() => self.skipWaiting()),
	);
});

self.addEventListener("activate", event => {
	event.waitUntil(
		caches
			.keys()
			.then(keys => Promise.all(keys.filter(k => k.startsWith("omp-collab-") && k !== CACHE).map(k => caches.delete(k))))
			.then(() => self.clients.claim()),
	);
});

self.addEventListener("fetch", event => {
	const req = event.request;
	if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
	// Navigations (including share-target URLs with a query) all get the shell; the
	// room link lives in the fragment, which never reaches the worker.
	const key = req.mode === "navigate" ? "./" : req;
	event.respondWith(
		caches.open(CACHE).then(cache => cache.match(key, { ignoreSearch: true })).then(hit => hit || fetch(req)),
	);
});
`;

await Bun.write(path.join(dist, "sw.js"), sw);
console.log(`build-sw: dist/sw.js (${files.length} files, cache omp-collab-${version})`);
